src/application/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^message/', include('message.urls', namespace='message')),
    url(r'^classes/', include('classes.urls', namespace='classes')),
    url(r'^', include('users.urls', namespace='users')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/post/urls.py
from django.conf.urls import url
from .views import *
from classes.views import PostUpdate
from django.contrib import admin

urlpatterns = [
    url(r'^$', PostsList.as_view(), name="post"),
    url(r'^(?P<pk>\d+)/$', PostUpdate.as_view(), name="detail"),
]

src/users/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth.views import login, logout
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'users/$', UserList.as_view(), name='list_users'),
    url(r'home/$', home, name='home'),
    url(r'^(?P<pk>\d+)/$', Show_user.as_view(), name="detail"),
    url(r'^login/', login, {'template_name': 'users/login.html'}, name="login"),
    url(r'^logout/', logout, {'next_page': '../home'}, name="logout"),
    url(r'^registration/', Registration.as_view(), name="registration"),
    url(r'^self_room/', Self_room.as_view(), name="self_room"),
    url(r'^self_update/', Self_update.as_view(), name="self_update"),
    url(r'^registration_complete/', registration_complete, name="registration_complete"),
]

src/users/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    rating = models.IntegerField(default=0)
    avatar = models.ImageField(upload_to='avatars', blank=True, null=True)
    proffession = models.IntegerField(default=0)

    def __unicode__(self):
        return u'{} {} {} {} {}'.format(self.first_name, self.last_name,  self.email, self.rating, self.avatar)

    def get_messages(self):
        return self.messages

src/users/views.py
from django.shortcuts import render, reverse, HttpResponse, HttpResponseRedirect
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from .models import User


def home(request):
    return render(request, 'users/home.html')


class UserList(ListView):
    template_name = 'users/list_users.html'
    context_object_name = 'list_users'
    model = User


class Show_user(DetailView):
    template_name = 'users/deteled_user.html'
    context_object_name = 'us'
    model = User


class Registration(CreateView):
    template_name = 'users/registration.html'
    model = User
    fields = ['username', 'password', 'first_name', 'email', 'last_name', 'proffession', 'avatar']

    def get_success_url(self):
        return reverse('users:registration_complete')


def registration_complete(request):
    return render(request, 'users/registration_complete.html')


class Self_room(ListView):
    template_name = 'users/self_room.html'
    model = User
    fields = ('last_name', 'avatar', 'first_name')


class Self_update(UpdateView):
    template_name = 'users/self_update.html'
    model = User
    fields = ('last_name', 'avatar', 'first_name')

    def get_success_url(self):
        return reverse('users:self_room')

    def get_object(self, queryset=None):
        return self.request.user

src/users/templates/users/deteled_user.html
{% extends "base.html" %}
{% block content %}
<div class="col-md-4 col-md-offset-4 post">
    {% if us.avatar %}
    <img class="avatar"src="{{ us.avatar.url }}" width="200px" height="120px">
    {% endif %}
    <p>{{us.first_name}}
    {{user.last_name}}</p>
    <p>Рейтинг: {{us.rating}}</p>
    <p>E-mail: {{us.email}}</p>
    <p>Статус: {% if us.proffession == 0 %}ученик{% else %} учитель{% endif %}</p>
    </div>
{% endblock %}

src/users/templates/users/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<a href="../users">Список пользователей</a>
<a href="../post">Список постов</a>
<a href="../classes">Список классов</a>
<a href="../message">Список сообщений</a>
<img class="shape shape-1 zoomTarget" src="{% static "img/class1.jpg" %}" >
<img class="shape shape-2 zoomTarget" src="{% static "img/class2.jpg" %}" >
<img class="shape shape-3 zoomTarget" src="{% static "img/class2.jpg" %}" >
<img class="shape shape-4 zoomTarget" src="{% static "img/class1.jpg" %}" >
<div class="center"><h3>SCHOGRAM - лучшее решение для учеников и учителей!</h3></div>

{% endblock %}

src/users/templates/users/list_users.html
{% extends "base.html" %}
{% block content %}
<a href="../home">Назад</a>
{% for us in object_list %}
    <div>
        {% if us.avatar %}
         <img class="avatar"src="{{ us.avatar.url }}" width="200px">
        {% endif %}
        <h1>Login: <a href="../{{us.id}}/">{{us.username}}</a></h1>
    <h2>Name: {{us.first_name}}</h2>
    <h3>Surname: {{us.last_name}}</h3>
    <h4>Rating: {{us.rating}}</h4>
    <p>E-mail: {{us.email}}</p>
    <b>Proffession: {{us.proffession}}</b>
    </div>

{% endfor %}
{% endblock %}

src/users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-md-3 col-md-offset-5 post">
    <form method="post">
        {% csrf_token %}
    {{ form|crispy}}
       <input type="submit" class="btn btn-primary" value="Войти">
    {{ form.errors }}
    </form>
</div>
{% endblock %}

src/users/templates/users/registration.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-md-3 col-md-offset-5 post">
<h1>Регистрация</h1>
        <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}

                <input type="submit" class="btn btn-primary" value="Зарегистироваться">
        </form>
</div>
{% endblock %}

src/users/templates/users/registration_complete.html
{% extends "base.html" %}
{% block content %}
<h2>Поздравляем! Вы успешно зарегестрировались на сайте</h2>

{% endblock %}

src/users/templates/users/self_room.html
{% extends "base.html" %}
{% block content %}
<div class="col-md-4 col-md-offset-4 post">
    <h3>Здравствуйте, {{user.username}}</h3>
    <h3>Ваши данные:</h3>
    {% if user.avatar %}
    <img class="avatar"src="{{ user.avatar.url }}" width="200px">
    {% endif %}
    <p>{{user.first_name}}
    {{user.last_name}}</p>
    <p>Рейтинг: {{user.rating}}</p>
    <p>E-mail: {{user.email}}</p>
    <p>Статус: {% if user.proffession == 0 %}ученик{% else %} учитель{% endif %}</p>
<a href="{% url 'users:self_update' %}">редактировать</a>
</div>
{% endblock %}

src/users/templates/users/self_update.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<div class="col-md-3 col-md-offset-5 post">
   <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}

                <input type="submit" class="btn btn-primary" value="Изменить">
        </form>
</div>
{% endblock %}