src/application/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^message/', include('message.urls', namespace='message')),
    url(r'^classes/', include('classes.urls', namespace='classes')),
    url(r'^', include('users.urls', namespace='users')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/message/urls.py
from django.conf.urls import url
from .views import *
from django.contrib import admin

urlpatterns = [
    url(r'^$', MessageList.as_view(), name="message"),
    url(r'^(?P<pk>\d+)/$', Dialogs.as_view(), name="detail"),
    url(r'^(?P<pk>\d+)/create/$', createmessage, name="create"),
    url(r'^(?P<pk>\d+)/form_message/$', FormMessage.as_view(), name="form_message")
]

src/post/urls.py
from django.conf.urls import url
from .views import *
from classes.views import PostUpdate
from django.contrib import admin

urlpatterns = [
    url(r'^$', PostsList.as_view(), name="post"),
    url(r'^(?P<pk>\d+)/$', PostUpdate.as_view(), name="detail"),
]

src/message/models.py
from __future__ import unicode_literals
from users.models import User
from django.db import models


class Dialog(models.Model):
    members = models.ManyToManyField(User)
    name = models.CharField(max_length=100)


class Message(models.Model):
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True, blank=True)
    author = models.ForeignKey(User)
    dial = models.ForeignKey(Dialog)

src/post/models.py
from __future__ import unicode_literals
from django.db import models
from users.models import User
from classes.models import Classes


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User)
    avatar = models.ImageField(upload_to='avatars', blank=True, null=True)
    clasz = models.ForeignKey(Classes)

    def __unicode__(self):
        return u'{} {} {}'.format(self.title, self.created_at, self.author.username)

    def count_likes(self):
        return self.likes.count()

src/message/views.py
# coding=utf-8
#utf-8
from django.shortcuts import render, get_object_or_404, reverse, HttpResponse, HttpResponseRedirect, redirect
from django.views.generic import DetailView, CreateView, ListView, UpdateView,View
from .models import Message
from .models import Dialog
from .models import User
from django import forms
from django.http import JsonResponse


class MessageList(CreateView):
    template_name = 'message/list_message.html'
    model = Message
    fields = ['text']

    def dispatch(self, request, pk=None, *args, **kwargs):
        self.dialog = Dialog.objects.all()
        return super(MessageList, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(MessageList, self).get_context_data(**kwargs)
        context['list_message'] = self.dialog
        return context

    def get_success_url(self):
        return reverse('message:message')


class FormMessage(DetailView):
    model = Dialog
    template_name = 'message/form_message.html'


class MessageForm(forms.Form):
    text = forms.CharField(max_length=255)


def createmessage(request, pk):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        print("I AM HERE")
        if form.is_valid():
            print("I AM HERE!")
            data = form.cleaned_data
            print(request)
            m = Message(
                text=data['text'],
                dial=Dialog.objects.get(id=pk),
                author=request.user,
            )
            m.save()
            return HttpResponse('Сообщение отправлено!')
    return HttpResponse('Ошибка при отправке сообщения')


class Dialogs(DetailView):
    template_name = 'message/dialog.html'
    model = Dialog


class NewMessage(CreateView):
    template_name = 'message/list_message.html'
    model = Message
    fields = ['text', 'author']

    def form_valid(self, form):
        return super(NewMessage, self).form_valid(form)


class AjaxableResponseMixin(object):
    def form_invalid(self, form):
        response = super(AjaxableResponseMixin, self).form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        response = super(AjaxableResponseMixin, self).form_valid(form)
        if self.request.is_ajax():
            data = {
                'pk': self.object.pk,
            }
            return JsonResponse(data)
        else:
            return response


class MessageCreate(AjaxableResponseMixin, CreateView):
    model = Message
    fields = ['text']

src/message/templates/message/dialog.html
{% load crispy_forms_tags %}
{% for mess in dialog.message_set.all %}
        <div class="mess_text animated " >
        <img class="user_avatar_message"src="{{mess.author.avatar.url}}">
        <p>{{mess.text}}</p>
        <p class="mess_date">{{mess.date}}</p>
        </div>
    {% endfor%}

src/message/templates/message/form_message.html
<div class="mess_text">
        <form class="ajax-form" method="post" data-dialogcreate="#create{{dialog.id}}"
         data-dialogformload="/message/{{dialog.id}}/form_message/" action="{% url 'message:create' dialog.id%}">
                {% csrf_token %}
                <textarea class="textarea form-control" cols="40" id="id_content" name="text" rows="10" required=""></textarea>
            <input type="submit" class="btn btn-primary mess_input" value="Ответить">
        </form>
      </div>

src/message/templates/message/list_message.html
{% load crispy_forms_tags %}
{% load staticfiles %}
<script src='{% static 'js/dialog_ready.js' %}'>
</script>
<script src='{% static 'js/close_dialog.js' %}'>
</script>
<div class="post sms animated" id="sms">
<div class='close'><img src="{% static "img/close.png" %}" width=20px></div>
{% for dialog in list_message %}
    <div class="dialog_name" data-dialog="{{dialog.id}}" data-dialogid="#dialog{{dialog.id}}"
         data-dialogload="/message/{{dialog.id}}/" data-dialogcreate="#create{{dialog.id}}"
         data-dialogformload="/message/{{dialog.id}}/form_message/">
    {{dialog.name}}
    </div>
    <div class="dialog" >
    <div class="dial" id="dialog{{dialog.id}}">

    </div>
    <div class="dialcreate"id="create{{dialog.id}}">

        </div>
    </div>
{% endfor %}
</div>