src/application/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^message/', include('message.urls', namespace='message')),
    url(r'^classes/', include('classes.urls', namespace='classes')),
    url(r'^', include('users.urls', namespace='users')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/classes/urls.py
from django.conf.urls import url
from .views import *
from django.contrib import admin

urlpatterns = [
    url(r'^$', ClassList.as_view(), name="classes"),
    url(r'^$', ClassList.as_view(), name="classes"),
    url(r'^(?P<pk>\d+)/$', PostsList.as_view(),  {'foo': 'bar'}, name="detail"),
]

src/post/urls.py
from django.conf.urls import url
from .views import *
from classes.views import PostUpdate
from django.contrib import admin

urlpatterns = [
    url(r'^$', PostsList.as_view(), name="post"),
    url(r'^(?P<pk>\d+)/$', PostUpdate.as_view(), name="detail"),
]

src/users/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth.views import login, logout
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'users/$', UserList.as_view(), name='list_users'),
    url(r'home/$', home, name='home'),
    url(r'^(?P<pk>\d+)/$', Show_user.as_view(), name="detail"),
    url(r'^login/', login, {'template_name': 'users/login.html'}, name="login"),
    url(r'^logout/', logout, {'next_page': '../home'}, name="logout"),
    url(r'^registration/', Registration.as_view(), name="registration"),
    url(r'^self_room/', Self_room.as_view(), name="self_room"),
    url(r'^self_update/', Self_update.as_view(), name="self_update"),
    url(r'^registration_complete/', registration_complete, name="registration_complete"),
]

src/users/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    rating = models.IntegerField(default=0)
    avatar = models.ImageField(upload_to='avatars', blank=True, null=True)
    proffession = models.IntegerField(default=0)

    def __unicode__(self):
        return u'{} {} {} {} {}'.format(self.first_name, self.last_name,  self.email, self.rating, self.avatar)

    def get_messages(self):
        return self.messages

src/users/views.py
from django.shortcuts import render, reverse, HttpResponse, HttpResponseRedirect
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from .models import User


def home(request):
    return render(request, 'users/home.html')


class UserList(ListView):
    template_name = 'users/list_users.html'
    context_object_name = 'list_users'
    model = User


class Show_user(DetailView):
    template_name = 'users/deteled_user.html'
    context_object_name = 'us'
    model = User


class Registration(CreateView):
    template_name = 'users/registration.html'
    model = User
    fields = ['username', 'password', 'first_name', 'email', 'last_name', 'proffession', 'avatar']

    def get_success_url(self):
        return reverse('users:registration_complete')


def registration_complete(request):
    return render(request, 'users/registration_complete.html')


class Self_room(ListView):
    template_name = 'users/self_room.html'
    model = User
    fields = ('last_name', 'avatar', 'first_name')


class Self_update(UpdateView):
    template_name = 'users/self_update.html'
    model = User
    fields = ('last_name', 'avatar', 'first_name')

    def get_success_url(self):
        return reverse('users:self_room')

    def get_object(self, queryset=None):
        return self.request.user

src/users/templates/base.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<html lang="RU" xmlns="http://www.w3.org/1999/html">
<head>
 <script src='{% static 'js/jquery.js' %}'></script>
    <script src='{% static 'js/jquery.zoomooz.min.js' %}'></script>
    <link rel="stylesheet" href="{% static "css/base.css" %}" type="text/css" />
    <link rel="stylesheet" href="{% static "css/animate.css" %}" type="text/css" />
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" type="text/css" />
    <script src='{% static 'js/message.js' %}'></script>
    <script src='{% static 'js/animate.js' %}'></script>

</head>
<body style="height: 100%">
<img class="back" src="{% static "img/back.jpg" %}" >
<div class="content_menu">
    <a href="{% url 'users:home' %}"><img class="home animated" id="content-menu-home" src="{%static "img/r1.png" %}" onmouseover="animation('content-menu-home', 'jello')"></a>
    <a><img class="mess animated" id="content-menu-message" src="{%static "img/message.png" %}" onmouseover="animation('content-menu-message', 'jello')"></a>
    <div class="maintitle"><h3>SCHOGRAM</h3></div>
</div>
    <nav>
    <div class="col-md-1 animjello animated" id="content-menu-1" ><a href="../">Назад</a></div>
   <div class="col-md-3 animated " id="content-menu-2" onmouseover="animation('content-menu-2', 'jello')"><a href="../">Тесты</a></div>

    <div class="col-md-2 animated" id="content-menu-3" onmouseover="animation('content-menu-3', 'jello')"><a href="{% url 'classes:classes'%}">Классы</a></div>
    <div class="col-md-2 animated" id="content-menu-4" onmouseover="animation('content-menu-4', 'jello')"><a href="../post">Посты</a></div>
    <div class="col-md-1"></div>
        {% if user.is_authenticated %}
     <div class="col-md-2 animated" id="content-menu-5" onmouseover="animation('content-menu-5', 'jello')"><a href="{% url 'users:self_room' %}">Личный кабиент</a></div>
    <div class="col-md-1 animated" id="content-menu-6" onmouseover="animation('content-menu-6', 'jello')"><a href="{% url 'users:logout' %}">Выход</a></div>
         {% else %}
    <div class="col-md-2 animated" id="content-menu-7" onmouseover="animation('content-menu-7', 'jello')"><a href="{% url 'users:registration' %}">Регистрация</a></div>
    <div class="col-md-1 animated" id="content-menu-8" onmouseover="animation('content-menu-8', 'jello')"><a href="{% url 'users:login' %}">Вход</a></div>
    {% endif %}

    </nav>
    <div class="content">
{% block content %}
{% endblock %}
    <div class="content-dialog">
    </div>
    </div>
</body>
</html>

src/users/templates/home.html
{% extends "base.html" %}
{% block content %}
<a href="users">Список пользователей</a>
<a href="posts">Список постов</a>
<a href="users">Список лайков</a>
<a href="users">Список сообщений</a>
{% endblock %}